<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <UseWindowsForms>true</UseWindowsForms>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Gondwana.Hosting\Gondwana.Hosting.csproj" />
      <ProjectReference Include="..\..\Gondwana.Widgets\Gondwana.Widgets.csproj" />
      <ProjectReference Include="..\..\Gondwana.WinForms.Hosting\Gondwana.WinForms.Hosting.csproj" />
      <ProjectReference Include="..\..\Gondwana.WinForms\Gondwana.WinForms.csproj" />
      <ProjectReference Include="..\..\Gondwana\Gondwana.csproj" />
    </ItemGroup>

    <!--
        Add your asset files here so they are copied to the output directory.
        Example:
        <ItemGroup>
            <Content Include="assets\my-sprite.png">
                <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            </Content>
        </ItemGroup>
    -->

</Project>
