namespace Gondwana.Studio.Documents;

/// <summary>
/// Captures provenance details for a tilesheet definition loaded in the editor.
/// </summary>
public sealed class TilesheetDefinitionSource
{
    private TilesheetDefinitionSource() { }

    /// <summary>
    /// Gets the high-level source kind.
    /// </summary>
    public TilesheetDefinitionSourceKind Kind { get; private init; }

    /// <summary>
    /// Gets the .gts path when loaded from a loose definition file.
    /// </summary>
    public string? GtsFilePath { get; private init; }

    /// <summary>
    /// Gets the .gaf path when loaded from a packed definition file.
    /// </summary>
    public string? AssetsFilePath { get; private init; }

    /// <summary>
    /// Gets the packed entry name when loaded from a packed definition file.
    /// </summary>
    public string? AssetEntryName { get; private init; }

    /// <summary>
    /// Creates a source marker for a loose .gts file.
    /// </summary>
    /// <param name="gtsFilePath">The loose .gts file path.</param>
    /// <returns>A source descriptor for a loose definition file.</returns>
    /// <exception cref="ArgumentException">Thrown when <paramref name="gtsFilePath"/> is null or whitespace.</exception>
    public static TilesheetDefinitionSource LooseDefinitionFile(string gtsFilePath)
    {
        if (string.IsNullOrWhiteSpace(gtsFilePath))
            throw new ArgumentException("GTS file path must be a non-empty string.", nameof(gtsFilePath));

        return new TilesheetDefinitionSource
        {
            Kind = TilesheetDefinitionSourceKind.LooseDefinitionFile,
            GtsFilePath = gtsFilePath
        };
    }

    /// <summary>
    /// Creates a source marker for a packed .gts entry inside an assets file.
    /// </summary>
    /// <param name="assetsFilePath">The assets file path.</param>
    /// <param name="assetEntryName">The packed .gts entry name.</param>
    /// <returns>A source descriptor for a packed definition file.</returns>
    /// <exception cref="ArgumentException">Thrown when required arguments are null or whitespace.</exception>
    public static TilesheetDefinitionSource PackedDefinitionFile(string assetsFilePath, string assetEntryName)
    {
        if (string.IsNullOrWhiteSpace(assetsFilePath))
            throw new ArgumentException("Assets file path must be a non-empty string.", nameof(assetsFilePath));

        if (string.IsNullOrWhiteSpace(assetEntryName))
            throw new ArgumentException("Asset entry name must be a non-empty string.", nameof(assetEntryName));

        return new TilesheetDefinitionSource
        {
            Kind = TilesheetDefinitionSourceKind.PackedDefinitionFile,
            AssetsFilePath = assetsFilePath,
            AssetEntryName = assetEntryName
        };
    }

    /// <summary>
    /// Creates a source marker for definitions generated by tooling.
    /// </summary>
    /// <returns>A source descriptor for generated definitions.</returns>
    public static TilesheetDefinitionSource Generated() =>
        new()
        {
            Kind = TilesheetDefinitionSourceKind.Generated
        };

    /// <summary>
    /// Creates an empty source marker when no provenance is known.
    /// </summary>
    /// <returns>A source descriptor with no provenance.</returns>
    public static TilesheetDefinitionSource None() =>
        new()
        {
            Kind = TilesheetDefinitionSourceKind.None
        };
}

/// <summary>
/// Indicates where a tilesheet definition came from.
/// </summary>
public enum TilesheetDefinitionSourceKind
{
    None = 0,
    LooseDefinitionFile = 1,
    PackedDefinitionFile = 2,
    Generated = 3
}
