<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
    <OutputType>WinExe</OutputType>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="assets\bubble-blue.png" />
    <None Remove="assets\bubble-green.png" />
    <None Remove="assets\bubble-pink.png" />
    <None Remove="assets\bubble-red.png" />
    <None Remove="assets\bubble-yellow.png" />
    <None Remove="assets\clouds_slice.png" />
    <None Remove="assets\sounovamusic-puzzle-amp-casual-game-music-460543.mp3" />
    <None Remove="assets\sounovamusic-puzzle-amp-casual-game-music-460543.txt" />
    <None Remove="assets\spot.png" />
    <None Remove="dorian.mid" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="assets\bubble-blue.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\bubble-green.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\bubble-pink.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\bubble-red.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\bubble-yellow.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\clouds_slice.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\dorian.mid">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\sounovamusic-puzzle-amp-casual-game-music-460543.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\sounovamusic-puzzle-amp-casual-game-music-460543.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\spot.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\tada.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Gondwana.Audio.Midi\Gondwana.Audio.Midi.csproj" />
    <ProjectReference Include="..\..\Gondwana.Hosting\Gondwana.Hosting.csproj" />
    <ProjectReference Include="..\..\Gondwana.WinForms.Hosting\Gondwana.WinForms.Hosting.csproj" />
    <ProjectReference Include="..\..\Gondwana.WinForms\Gondwana.WinForms.csproj" />
    <ProjectReference Include="..\..\Gondwana\Gondwana.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="GameWindow.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>