<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <!-- URLs / repository -->
        <PackageProjectUrl>https://github.com/Isthimius/Gondwana/tree/master/Gondwana.Avalonia.Hosting</PackageProjectUrl>

        <!-- NuGet packaging -->
        <IsPackable>true</IsPackable>
        <PackageId>Gondwana.Avalonia.Hosting</PackageId>
        <Title>Gondwana Avalonia Hosting</Title>
        <Description>Avalonia hosting implementation for the Gondwana Game Engine, providing an Avalonia-specific game host for application startup, lifecycle management, and adapter integration across desktop, WASM, Android, iOS, and macOS.</Description>
        <PackageTags>game-engine gamedev csharp dotnet avalonia hosting cross-platform desktop wasm android ios macos bootstrap lifecycle game-loop initialization engine-host</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>gondwana-logo.png</PackageIcon>
		<PackageReleaseNotes>Full changelog: https://github.com/Isthimius/Gondwana/blob/master/CHANGELOG.md</PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Gondwana.Hosting\Gondwana.Hosting.csproj" />
        <ProjectReference Include="..\Gondwana.Avalonia\Gondwana.Avalonia.csproj" />
        <ProjectReference Include="..\Gondwana\Gondwana.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="" />
		<None Include="CHANGELOG.md" Pack="true" PackagePath="" />
        <None Include="..\gondwana-logo.png" Pack="true" PackagePath="" Link="gondwana-logo.png" />
    </ItemGroup>

</Project>
