using System.ComponentModel;
using System.Text;
using Gondwana.Assets;
using Spectre.Console;
using Spectre.Console.Cli;

namespace Gondwana.Cli.Commands.Assets;

internal sealed class AssetsGenerateKeysCommand : Command<AssetsGenerateKeysCommand.Settings>
{
    public sealed class Settings : CommandSettings
    {
        [CommandArgument(0, "<file>")]
        [Description("The asset file to generate keys from.")]
        public string File { get; init; } = string.Empty;

        [CommandOption("-o|--output")]
        [Description("Output .cs file path. If omitted, prints to stdout.")]
        public string? Output { get; init; }

        [CommandOption("-n|--namespace")]
        [Description("C# namespace for the generated class.")]
        public string? Namespace { get; init; }

        [CommandOption("-c|--class")]
        [Description("C# class name (default: AssetKeys).")]
        [DefaultValue("AssetKeys")]
        public string ClassName { get; init; } = "AssetKeys";
    }

    protected override int Execute(CommandContext context, Settings settings, CancellationToken cancellationToken)
    {
        var path = Path.GetFullPath(settings.File);

        if (!System.IO.File.Exists(path))
        {
            AnsiConsole.MarkupLine($"[red]File not found: {Markup.Escape(path)}[/]");
            return 1;
        }

        AssetsFile assetFile;
        try
        {
            assetFile = AssetsFile.LoadOrCreate(path);
        }
        catch (Exception ex)
        {
            AnsiConsole.MarkupLine($"[red]Failed to open asset file: {Markup.Escape(ex.Message)}[/]");
            return 1;
        }

        using (assetFile)
        {
            var entries = assetFile.GetAllEntries()
                                   .OrderBy(e => e.AssetType)
                                   .ThenBy(e => e.AssetName)
                                   .ToList();

            if (entries.Count == 0)
            {
                AnsiConsole.MarkupLine("[yellow]No assets found in the file — nothing to generate.[/]");
                return 0;
            }

            var code = GenerateCode(entries, settings.ClassName, settings.Namespace);

            if (settings.Output is not null)
            {
                var outputPath = Path.GetFullPath(settings.Output);

                try
                {
                    var outputDirectory = Path.GetDirectoryName(outputPath);
                    if (!string.IsNullOrEmpty(outputDirectory))
                    {
                        System.IO.Directory.CreateDirectory(outputDirectory);
                    }

                    System.IO.File.WriteAllText(outputPath, code, Encoding.UTF8);
                    AnsiConsole.MarkupLine($"[green]Generated {Markup.Escape(outputPath)} with {entries.Count} key(s).[/]");
                }
                catch (System.UnauthorizedAccessException ex)
                {
                    AnsiConsole.MarkupLine($"[red]Failed to write output file: {Markup.Escape(ex.Message)}[/]");
                    return 1;
                }
                catch (System.IO.IOException ex)
                {
                    AnsiConsole.MarkupLine($"[red]Failed to write output file: {Markup.Escape(ex.Message)}[/]");
                    return 1;
                }
            }
            else
            {
                Console.Write(code);
            }
        }

        return 0;
    }

    private static string GenerateCode(
        IReadOnlyList<AssetsFileEntry> entries,
        string className,
        string? namespaceName)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by Gondwana CLI — do not edit manually.");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        foreach (var group in entries.GroupBy(e => e.AssetType))
        {
            sb.AppendLine($"    // {group.Key}");

            foreach (var entry in group)
            {
                var constName = ToConstantName(entry.AssetName);
                sb.AppendLine($"    public const string {constName} = \"{entry.AssetName}\";");
            }

            sb.AppendLine();
        }

        // Remove trailing blank line inside the class.
        if (sb.Length > 0 && sb[^1] == '\n')
        {
            var eol = sb.ToString().EndsWith("\r\n") ? 2 : 1;
            sb.Remove(sb.Length - eol, eol);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string ToConstantName(string assetName)
    {
        // Convert path-like names such as "sprites/player.png" → "SpritesPlayerPng".
        var parts = assetName
            .Split(['/', '\\', '.', '-', '_', ' '], StringSplitOptions.RemoveEmptyEntries)
            .Where(p => p.Length > 0)
            .Select(p => char.ToUpperInvariant(p[0]) + (p.Length > 1 ? p[1..] : string.Empty));

        var name = string.Concat(parts);

        // Ensure the identifier starts with a letter.
        if (name.Length > 0 && !char.IsLetter(name[0]))
            name = "_" + name;

        return name;
    }
}
