using System.ComponentModel;
using System.Text;
using Gondwana.Assets;
using Spectre.Console;
using Spectre.Console.Cli;

namespace Gondwana.Cli.Commands.Assets;

internal sealed class AssetsGenerateKeysCommand : Command<AssetsGenerateKeysCommand.Settings>
{
    public sealed class Settings : CommandSettings
    {
        [CommandArgument(0, "<file>")]
        [Description("The asset file to generate keys from.")]
        public string File { get; init; } = string.Empty;

        [CommandOption("-o|--output")]
        [Description("Output .cs file path. If omitted, prints to stdout.")]
        public string? Output { get; init; }

        [CommandOption("-n|--namespace")]
        [Description("C# namespace for the generated class.")]
        public string? Namespace { get; init; }

        [CommandOption("-c|--class")]
        [Description("C# class name (default: AssetKeys).")]
        [DefaultValue("AssetKeys")]
        public string ClassName { get; init; } = "AssetKeys";
    }

    protected override int Execute(CommandContext context, Settings settings, CancellationToken cancellationToken)
    {
        var path = Path.GetFullPath(settings.File);

        if (!System.IO.File.Exists(path))
        {
            AnsiConsole.MarkupLine($"[red]File not found: {Markup.Escape(path)}[/]");
            return 1;
        }

        AssetsFile assetFile;
        try
        {
            assetFile = AssetsFile.LoadOrCreate(path);
        }
        catch (Exception ex)
        {
            AnsiConsole.MarkupLine($"[red]Failed to open asset file: {Markup.Escape(ex.Message)}[/]");
            return 1;
        }

        using (assetFile)
        {
            var entries = assetFile.GetAllEntries()
                                   .OrderBy(e => e.AssetType)
                                   .ThenBy(e => e.AssetName)
                                   .ToList();

            if (entries.Count == 0)
            {
                AnsiConsole.MarkupLine("[yellow]No assets found in the file — nothing to generate.[/]");
                return 0;
            }

            var code = GenerateCode(entries, settings.ClassName, settings.Namespace);

            if (settings.Output is not null)
            {
                var outputPath = Path.GetFullPath(settings.Output);

                try
                {
                    var outputDirectory = Path.GetDirectoryName(outputPath);
                    if (!string.IsNullOrEmpty(outputDirectory))
                    {
                        System.IO.Directory.CreateDirectory(outputDirectory);
                    }

                    System.IO.File.WriteAllText(outputPath, code, Encoding.UTF8);
                    AnsiConsole.MarkupLine($"[green]Generated {Markup.Escape(outputPath)} with {entries.Count} key(s).[/]");
                }
                catch (System.UnauthorizedAccessException ex)
                {
                    AnsiConsole.MarkupLine($"[red]Failed to write output file: {Markup.Escape(ex.Message)}[/]");
                    return 1;
                }
                catch (System.IO.IOException ex)
                {
                    AnsiConsole.MarkupLine($"[red]Failed to write output file: {Markup.Escape(ex.Message)}[/]");
                    return 1;
                }
            }
            else
            {
                Console.Write(code);
            }
        }

        return 0;
    }

    private static string GenerateCode(
        IReadOnlyList<AssetsFileEntry> entries,
        string className,
        string? namespaceName)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by Gondwana CLI — do not edit manually.");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        // Track generated identifier → usage count for de-duplication across the whole class.
        var usedNames = new Dictionary<string, int>(StringComparer.Ordinal);

        foreach (var group in entries.GroupBy(e => e.AssetType))
        {
            sb.AppendLine($"    // {group.Key}");

            foreach (var entry in group)
            {
                var baseName = ToConstantName(entry.AssetName);

                // De-duplicate: if the name was used before, append an incrementing suffix.
                string constName;
                if (usedNames.TryGetValue(baseName, out var count))
                {
                    usedNames[baseName] = count + 1;
                    constName = $"{baseName}{count + 1}";
                }
                else
                {
                    usedNames[baseName] = 1;
                    constName = baseName;
                }

                var escapedValue = EscapeStringLiteral(entry.AssetName);
                sb.AppendLine($"    public const string {constName} = \"{escapedValue}\";");
            }

            sb.AppendLine();
        }

        // Remove trailing blank line inside the class.
        if (sb.Length > 0 && sb[^1] == '\n')
        {
            var eol = sb.ToString().EndsWith("\r\n") ? 2 : 1;
            sb.Remove(sb.Length - eol, eol);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    // C# contextual and reserved keywords that cannot be used as unescaped identifiers.
    private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
        "checked", "class", "const", "continue", "decimal", "default", "delegate", "do",
        "double", "else", "enum", "event", "explicit", "extern", "false", "finally",
        "fixed", "float", "for", "foreach", "goto", "if", "implicit", "in", "int",
        "interface", "internal", "is", "lock", "long", "namespace", "new", "null",
        "object", "operator", "out", "override", "params", "private", "protected",
        "public", "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof",
        "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
        "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using",
        "virtual", "void", "volatile", "while",
    };

    private static string ToConstantName(string assetName)
    {
        // Split on common path/word separators, title-case each part, then join.
        var parts = assetName
            .Split(['/', '\\', '.', '-', '_', ' '], StringSplitOptions.RemoveEmptyEntries)
            .Select(p =>
            {
                // Remove any character that is not a letter, digit, or underscore.
                var sanitized = new string(p.Select(c =>
                    char.IsLetterOrDigit(c) || c == '_' ? c : '_').ToArray());

                if (sanitized.Length == 0)
                    return string.Empty;

                // Title-case the segment.
                return char.ToUpperInvariant(sanitized[0]) + (sanitized.Length > 1 ? sanitized[1..] : string.Empty);
            })
            .Where(p => p.Length > 0);

        var name = string.Concat(parts);

        if (name.Length == 0)
            name = "_Asset";

        // Ensure the identifier starts with a letter or underscore.
        if (!char.IsLetter(name[0]) && name[0] != '_')
            name = "_" + name;

        // Prefix reserved keywords so the generated code compiles.
        if (CSharpKeywords.Contains(name))
            name = "_" + name;

        return name;
    }

    /// <summary>Escapes backslashes and double-quotes for use inside a C# regular string literal.</summary>
    private static string EscapeStringLiteral(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
