<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <!-- URLs / repository -->
        <PackageProjectUrl>https://github.com/Isthimius/Gondwana/tree/master/Gondwana.Video</PackageProjectUrl>

        <!-- NuGet packaging -->
        <IsPackable>true</IsPackable>
        <PackageId>Gondwana.Video</PackageId>
        <Title>Gondwana Video Playback</Title>
        <Description>Video playback support for the Gondwana Game Engine, including integration for loading and rendering video content within the engine.</Description>
        <PackageTags>game-engine gamedev csharp dotnet video playback media rendering</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>gondwana-logo.png</PackageIcon>
		<PackageReleaseNotes>Full changelog: https://github.com/Isthimius/Gondwana/blob/master/CHANGELOG.md</PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="LibVLCSharp" Version="3.9.7" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Gondwana\Gondwana.csproj" />
    </ItemGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="" />
		<None Include="CHANGELOG.md" Pack="true" PackagePath="" />
		<None Include="..\gondwana-logo.png" Pack="true" PackagePath="" Link="gondwana-logo.png" />
	</ItemGroup>

</Project>
