<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Vorbis" Version="1.5.0" />
    <PackageReference Include="ppy.SDL2-CS" Version="1.0.82" />
    <PackageReference Include="SkiaSharp.Views.WindowsForms" Version="3.119.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gondwana\Gondwana.csproj" />
  </ItemGroup>

</Project>
