<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="C:\Users\MikeAdkins\.nuget\packages\ppy.sdl2-cs\1.0.82\contentFiles\any\netstandard2.0\app.config" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Vorbis" Version="1.5.0" />
    <PackageReference Include="SkiaSharp.Views.WindowsForms" Version="3.119.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gondwana\Gondwana.csproj" />
  </ItemGroup>

</Project>
