<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <OutputType>Library</OutputType>
        <RootNamespace>Gondwana.WinForms</RootNamespace>
        <AssemblyName>Gondwana.WinForms</AssemblyName>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <!-- URLs / repository -->
        <PackageProjectUrl>https://github.com/Isthimius/Gondwana/tree/master/Gondwana.WinForms</PackageProjectUrl>

        <!-- NuGet packaging -->
        <IsPackable>true</IsPackable>
        <PackageId>Gondwana.WinForms</PackageId>
        <Title>Gondwana WinForms Platform Support</Title>
        <Description>WinForms-based platform support for the Gondwana Game Engine, providing rendering, input, and audio integration for Windows desktop applications.</Description>
        <PackageTags>$(PackageTags) winforms windows desktop rendering input audio</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>gondwana-logo.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="C:\Users\mikel\.nuget\packages\naudio.vorbis\1.5.0\contentFiles\any\netstandard2.0\README.md" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="NAudio.Vorbis" Version="1.5.0" />
        <PackageReference Include="SkiaSharp.Views.WindowsForms" Version="3.119.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Gondwana\Gondwana.csproj" />
    </ItemGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="" />
		<None Include="..\gondwana-logo.png" Pack="true" PackagePath="" Link="gondwana-logo.png" />
	</ItemGroup>

</Project>
