<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Gondwana.Demos.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
        <IsPackable>false</IsPackable>
        <NoWarn>$(NoWarn);NU1701</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Gondwana.WinForms\Gondwana.WinForms.csproj" />
        <ProjectReference Include="..\..\Gondwana\Gondwana.csproj" />
    </ItemGroup>

</Project>
