<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <OutputType>WinExe</OutputType>
        <RootNamespace>Gondwana.Demos.SpotAvalonia</RootNamespace>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <ApplicationIcon>assets\spot_ico.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="assets\**\*" />
        <Content Include="assets\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Desktop" Version="11.3.13" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.13" />
        <PackageReference Include="Tmds.DBus.Protocol" Version="0.21.3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Spot.Shared\Spot.Shared.csproj" />
        <ProjectReference Include="..\..\Gondwana.Avalonia.Hosting\Gondwana.Avalonia.Hosting.csproj" />
        <ProjectReference Include="..\..\Gondwana.Avalonia\Gondwana.Avalonia.csproj" />
        <ProjectReference Include="..\..\Gondwana.Hosting\Gondwana.Hosting.csproj" />
        <ProjectReference Include="..\..\Gondwana.Widgets\Gondwana.Widgets.csproj" />
        <ProjectReference Include="..\..\Gondwana\Gondwana.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\Spot.Shared\Host\*.cs" Link="Hosts\%(Filename)%(Extension)" />
    </ItemGroup>

</Project>
