<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Gondwana.Demos.Spot</RootNamespace>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Gondwana.Widgets\Gondwana.Widgets.csproj" />
        <ProjectReference Include="..\..\Gondwana\Gondwana.csproj" />
    </ItemGroup>
</Project>
