<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
        <Company>Hidden Worlds Games</Company>
        <Product>Gondwana Game Engine</Product>
        <Authors>Michael Adkins</Authors>
        <Version>1.0.0</Version>
        <FileVersion>1.0.0</FileVersion>
        <InformationalVersion>1.0.0-alpha</InformationalVersion>
		<TargetFramework>net8.0</TargetFramework>
		<OutputType>Library</OutputType>
		<RootNamespace>Gondwana</RootNamespace>
		<AssemblyName>Gondwana</AssemblyName>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Audio\TimGM6mb.sf2" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0" />
	  <PackageReference Include="NAudio" Version="2.2.1" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	  <PackageReference Include="SharpZipLib" Version="1.4.2" />
	  <PackageReference Include="SkiaSharp" Version="3.119.1" />
	  <PackageReference Include="SkiaSharp.HarfBuzz" Version="3.119.1" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="gondwana.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
