<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ppy.SDL2-CS" Version="1.0.82" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gondwana\Gondwana.csproj" />
  </ItemGroup>

</Project>
