<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <!-- URLs / repository -->
        <PackageProjectUrl>https://github.com/Isthimius/Gondwana/tree/master/Gondwana.Input.SDL2</PackageProjectUrl>

        <!-- NuGet packaging -->
        <IsPackable>true</IsPackable>
        <PackageId>Gondwana.Input.SDL2</PackageId>
        <Title>Gondwana SDL2 Input Support</Title>
        <Description>SDL2-based input support for the Gondwana Game Engine, including gamepad and controller integration through the engine's input system.</Description>
        <PackageTags>game-engine gamedev csharp dotnet input sdl2 gamepad controller</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>gondwana-logo.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ppy.SDL2-CS" Version="1.0.82" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Gondwana\Gondwana.csproj" />
    </ItemGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="" />
		<None Include="..\gondwana-logo.png" Pack="true" PackagePath="" Link="gondwana-logo.png" />
	</ItemGroup>

</Project>
