using System.ComponentModel;
using Gondwana.Cli.Commands.Assets;
using Gondwana.Cli.Commands.Tilesheets;
using Spectre.Console;
using Spectre.Console.Cli;

namespace Gondwana.Cli.Commands;

internal sealed record ProjectDiagnostic(string Label, string Status, string Detail);

internal static class ProjectHealth
{
    public static IReadOnlyList<ProjectDiagnostic> Inspect(ProjectPackages project)
    {
        var results = new List<ProjectDiagnostic>();
        void Report(string label, string status, string detail) => results.Add(new(label, status, detail));
        Report("Project", "OK", Path.GetFileNameWithoutExtension(project.Path));
        var frameworks = ProjectHelper.GetTargetFrameworks(project.Path);
        Report("Target framework", frameworks.Count > 0 ? "OK" : "Warning", frameworks.Count > 0 ? string.Join(", ", frameworks) : "Not declared locally; may be imported.");
        Report("Host", project.Host is null ? "Warning" : "OK", project.Host ?? "Not determined (library, custom host, or multiple adapters).");
        var names = project.Packages.Select(p => p.Name).Concat(project.References).ToArray();
        Report("Gondwana references", names.Length == 0 ? (project.Limitations.Count > 0 ? "Warning" : "Fail") : "OK", names.Length == 0 ? "No local Gondwana references found; imported references may require MSBuild evaluation." : string.Join(", ", names));
        foreach (var package in project.Packages) Report(package.Name, "OK", package.Version ?? "Version unresolved/imported");
        foreach (var limitation in project.Limitations) Report("Project structure", "Warning", limitation);
        var versions = project.Packages.Select(p => ProjectPackages.Conditional(p.Reference) || p.Reference.Elements().Any(ProjectPackages.Conditional) ? null : p.Version).ToArray();
        if (versions.Any(v => !ProjectPackages.ExactVersion(v))) Report("Package versions", "Warning", "Some versions require MSBuild evaluation; only literal versions can be checked.");
        var known = versions.Where(ProjectPackages.ExactVersion).Distinct(StringComparer.OrdinalIgnoreCase).ToArray();
        Report("Package versions", known.Length > 1 ? "Fail" : "OK", known.Length > 1 ? "Mismatched versions: " + string.Join(", ", known) : "Known Gondwana package versions aligned.");
        if (project.Packages.Count > 0 && project.References.Count > 0) Report("Reference kinds", "Warning", "Mixed Gondwana package and source project references; verify compatibility.");
        if (project.Host is { } host && !names.Contains($"Gondwana.{host}.Hosting", StringComparer.OrdinalIgnoreCase))
            Report("Hosting package", "Warning", $"Gondwana.{host}.Hosting is absent. Optional for custom lifecycle code; use 'gondwana add hosting' if needed.");
        else if (project.Host is { } knownHost)
            Report("Hosting package", "OK", $"Gondwana.{knownHost}.Hosting");
        if (project.Host == "Blazor")
        {
            var native = names.Where(n => new[] { "Gondwana.Input.SDL2", "Gondwana.Audio.Midi", "Gondwana.Video" }.Contains(n, StringComparer.OrdinalIgnoreCase)).ToArray();
            if (native.Length > 0) Report("Browser packages", "Warning", "Native desktop dependencies referenced: " + string.Join(", ", native));
            var index = Path.Combine(Path.GetDirectoryName(project.Path)!, "wwwroot", "index.html");
            if (!File.Exists(index)) Report("Blazor index", "Warning", "wwwroot/index.html is missing; verify whether it is generated by the build.");
            foreach (var element in project.Project.Descendants().Where(e => e.Name.LocalName == "WasmEnableThreads" && !ProjectPackages.Conditional(e) && e.Value.Equals("false", StringComparison.OrdinalIgnoreCase)))
                Report("WASM threads", "Warning", "WasmEnableThreads is explicitly false; verify this is intended for the game.");
        }
        var root = Path.GetDirectoryName(project.Path)!;
        foreach (var item in project.Project.Descendants().Where(e => e.Name.LocalName is "ProjectReference" or "Content" or "EmbeddedResource" or "None"))
        {
            var include = item.Attribute("Include")?.Value;
            if (include is null || !ProjectPackages.Literal(include) || ProjectPackages.Conditional(item)) continue;
            var path = Path.GetFullPath(Path.Combine(root, include.Replace('\\', Path.DirectorySeparatorChar)));
            if (!File.Exists(path) && !Directory.Exists(path)) Report("Referenced file", item.Name.LocalName == "ProjectReference" ? "Fail" : "Warning", $"Missing {include}" + (item.Name.LocalName == "ProjectReference" ? "" : " (may be generated during build)"));
        }
        int bundles = 0, sheets = 0;
        foreach (var file in SourceFiles(root, (path, error) => Report(Path.GetRelativePath(root, path), "Warning", "Asset scan incomplete: " + error)))
        {
            var extension = Path.GetExtension(file).ToLowerInvariant();
            if (extension is not (".gts" or ".gaf" or ".assets")) continue;
            var label = Path.GetRelativePath(root, file);
            try
            {
                if (extension == ".gts")
                {
                    sheets++;
                    var inspection = TilesheetInspection.FromFile(file);
                    // Packed definitions can validly omit AssetsFilePath and receive
                    // their containing bundle at runtime. Loose project scans lack it.
                    var packedOnly = inspection.Definition?.Image is { FilePath: null, AssetsFilePath: null, AssetEntryName: not null };
                    foreach (var error in inspection.Errors) Report(label, packedOnly && error.StartsWith("Image:") ? "Warning" : "Fail", error);
                }
                else
                {
                    bundles++;
                    if (BundleHelper.NeedsPassword(file)) { Report(label, "Warning", "Protected bundle; use assets validate --password to inspect contents."); continue; }
                    foreach (var error in BundleHelper.ValidateContents(file, null)) Report(label, "Fail", error);
                }
            }
            catch (Exception ex) { Report(label, "Fail", ex.Message); }
        }
        Report("Asset scan", "OK", $"Inspected {bundles} bundle(s), {sheets} loose tilesheet(s); bin/obj and directory links excluded.");
        return results;
    }

    internal static IEnumerable<string> SourceFiles(string directory, Action<string, string> warning, Func<string, FileSystemInfo[]>? readEntries = null)
    {
        readEntries ??= path => new DirectoryInfo(path).GetFileSystemInfos();
        FileSystemInfo[]? entries = null;
        try { entries = readEntries(directory); }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException) { warning(directory, ex.Message); }
        if (entries is null) yield break;
        foreach (var entry in entries.OrderBy(e => e.FullName, StringComparer.Ordinal))
        {
            FileAttributes? attributes = null;
            try { attributes = entry.Attributes; }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException) { warning(entry.FullName, ex.Message); }
            if (attributes is null || (attributes & FileAttributes.ReparsePoint) != 0) continue;
            if ((attributes & FileAttributes.Directory) == 0) { yield return entry.FullName; continue; }
            if (new[] { "bin", "obj", ".git", ".vs", "node_modules" }.Contains(entry.Name, StringComparer.OrdinalIgnoreCase)) continue;
            foreach (var file in SourceFiles(entry.FullName, warning, readEntries)) yield return file;
        }
    }

    public static IReadOnlyList<string> Fix(ProjectPackages project)
    {
        project.EnsureEditable();
        var core = project.Packages.SingleOrDefault(p => p.Name.Equals("Gondwana", StringComparison.OrdinalIgnoreCase));
        if (core?.Version is not { } version || PackageVersions.StableNumber(version) is not { } coreVersion ||
            project.Packages.Any(p => PackageVersions.StableNumber(p.Version!) is not { } other || other > coreVersion))
            throw new InvalidOperationException("No unambiguous version fix: require a stable core version at least as new as every Gondwana reference. Use upgrade --version explicitly.");
        return project.Upgrade(version);
    }
}

internal sealed class CheckCommand : Command<CheckCommand.Settings>
{
    public sealed class Settings : ProjectSettings
    {
        [CommandOption("--fix")]
        [Description("Align older Gondwana packages to an explicit stable core version, then recheck. Does not rewrite source or select optional hosting.")]
        public bool Fix { get; init; }
    }

    protected override int Execute(CommandContext context, Settings settings, CancellationToken cancellationToken)
    {
        try
        {
            var project = ProjectCommand.Load(settings.Project);
            AnsiConsole.MarkupLine("[bold]Gondwana Project Check[/]");
            var result = Print(ProjectHealth.Inspect(project));
            if (!settings.Fix) return result;
            try
            {
                var changes = ProjectHealth.Fix(project);
                ProjectCommand.PrintChanges(changes);
                if (changes.Count > 0) project.Save();
            }
            catch (InvalidOperationException ex) { AnsiConsole.MarkupLine($"[yellow]No automatic fix:[/] {Markup.Escape(ex.Message)}"); }
            AnsiConsole.WriteLine("Re-checking...");
            return Print(ProjectHealth.Inspect(ProjectCommand.Load(settings.Project)));
        }
        catch (Exception ex) { return ProjectCommand.Fail(ex); }
    }

    private static int Print(IReadOnlyList<ProjectDiagnostic> results)
    {
        var table = new Table().AddColumn("Check").AddColumn("Status").AddColumn("Detail");
        foreach (var result in results)
        {
            var color = result.Status == "Fail" ? "red" : result.Status == "Warning" ? "yellow" : "green";
            table.AddRow(Markup.Escape(result.Label), $"[{color}]{result.Status}[/]", Markup.Escape(result.Detail));
        }
        AnsiConsole.Write(table);
        var failures = results.Count(r => r.Status == "Fail");
        AnsiConsole.WriteLine($"{failures} failure(s), {results.Count(r => r.Status == "Warning")} warning(s).");
        return failures == 0 ? 0 : 1;
    }
}
