<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Platform Condition=" '$(Platform)' == '' ">x64</Platform>
        <PlatformTarget>x64</PlatformTarget>

        <OutputType>WinExe</OutputType>
        <UseWindowsForms>true</UseWindowsForms>
        <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
        <RootNamespace>Gondwana.Demos.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
        <ApplicationIcon>assets\spot_ico.ico</ApplicationIcon>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <SelfContained>true</SelfContained>
        <PublishSingleFile>true</PublishSingleFile>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="assets\archive\**" />
      <Compile Remove="Properties\**" />
      <EmbeddedResource Remove="assets\archive\**" />
      <EmbeddedResource Remove="Properties\**" />
      <None Remove="assets\archive\**" />
      <None Remove="Properties\**" />
    </ItemGroup>


    <ItemGroup>
        <Content Include="assets\ArchitectsDaughter-Regular.ttf">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="assets\clouds.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="assets\freesound_community-080047_lose_funny_retro_video-game-80925.mp3">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="assets\freesound_community-bump-7-92964.mp3">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="assets\freesound_community-velcro_fast-91558.mp3">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="assets\freesound_community-water-drip-45622.mp3">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="assets\peekaboolabcreative-11l-victory_sound_with_t-1749487402950-357606.mp3">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="assets\sounovamusic-puzzle-amp-casual-game-music-460543.mp3">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="assets\sources.txt">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="assets\spot.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="assets\spot_ico.ico">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="assets\spot_ico.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="assets\gondwana-logo-text.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="assets\spot_selected.png">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="assets\spot_defaults.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="assets\spot_sheet.png">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\Gondwana.Hosting\Gondwana.Hosting.csproj" />
        <ProjectReference Include="..\..\Gondwana.WinForms.Hosting\Gondwana.WinForms.Hosting.csproj" />
        <ProjectReference Include="..\..\Gondwana.WinForms\Gondwana.WinForms.csproj" />
        <ProjectReference Include="..\..\Gondwana\Gondwana.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Compile Update="GameWindow.cs">
            <SubType>Form</SubType>
        </Compile>
    </ItemGroup>
    <ItemGroup>
      <None Update="assets\OFL.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>
</Project>
